spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update

  http:
    converters:
      preferred-json-mapper: gson

server:
  port: 8080

  ssl:
    enabled: false

telegram:
  webhook:
    bot:
      botToken: ${TOKEN}
      botUsername: ${USERNAME}
      botPath: ${BOTURL}